### ISSUE TITLE
Add support for double-tappable buttons

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#12]
See https://docs.hubitat.com/index.php?title=Driver_Capability_List#DoubleTapableButton

**Comment by SPCulhane** [comment]
thank you! looking forward to this

**Comment by SPCulhane** [comment]
I gave this a shot and its not working.
```
2020-02-19 07:27:48 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 361, in async_added_to_hass
    await self.async_enable()
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 423, in async_enable
    self._async_detach_triggers = await self._async_attach_triggers()
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 464, in _async_attach_triggers
    self.hass, conf, self.async_trigger, info
  File "/usr/src/homeassistant/homeassistant/components/automation/device.py", line 31, in async_attach_trigger
    return await platform.async_attach_trigger(hass, config, action, automation_info)
  File "/config/custom_components/hubitat/device_trigger.py", line 158, in async_attach_trigger
    raise InvalidDeviceAutomationConfig
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig
```

The option is there when creating an automation but there isn't any text:
![image](https://user-images.githubusercontent.com/790943/74834713-fa64f780-52e9-11ea-91c2-37794102498b.png)

```
- id: '1582115162734'
  alias: test
  description: ''
  trigger:
  - device_id: 087eaf0689f943d5b0cdd3ef21d67a20
    domain: hubitat
    platform: device
    subtype: '1'
    type: double tapped
  condition: []
  action:
  - entity_id: light.kitchen_dining_area_light
    service: light.turn_on
```

**Comment by jason0x43** [comment]
I published v0.4.3 which should fix the missing labels, and also added some additional logging statements to help diagnose trigger issues. You may need to delete and recreate double tap automations.

Let me know if that works any better.

**Comment by SPCulhane** [comment]
thank you for the quick fix. I can confirm the labels are displaying correcting and everything is working.

**Comment by jason0x43** [comment]
Great! Closing this as fixed.
