### ISSUE TITLE
Home Assistant 2021.7.0 - Integration 'hubitat' does not support device automation triggers 

### ISSUE THREAD

**Issue by SPCulhane** [jason0x43/hacs-hubitat#127]
Logger: homeassistant.config
Source: components/device_automation/__init__.py:91
First occurred: 12:52:41 PM (5 occurrences)
Last logged: 12:52:41 PM
Invalid config for [automation]: Integration 'hubitat' does not support device automation triggers (See ?, line ?).

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 85, in async_get_device_automation_platform
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hubitat/device_trigger.py", line 21, in <module>
    from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
ImportError: cannot import name 'TRIGGER_BASE_SCHEMA' from 'homeassistant.components.device_automation' (/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 104, in _try_async_validate_config_item
    config = await async_validate_config_item(hass, config, full_config)
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 72, in async_validate_config_item
    config[CONF_TRIGGER] = await async_validate_trigger_config(
  File "/usr/src/homeassistant/homeassistant/helpers/trigger.py", line 49, in async_validate_trigger_config
    conf = await platform.async_validate_trigger_config(hass, conf)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 17, in async_validate_trigger_config
    platform = await async_get_device_automation_platform(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 91, in async_get_device_automation_platform
    raise InvalidDeviceAutomationConfig(
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig: Integration 'hubitat' does not support device automation triggers

**Comment by SPCulhane** [comment]
if I had to guess, I would say it due to this:

https://www.home-assistant.io/blog/2021/07/07/release-20217/#trigger-conditions-and-trigger-ids

**Comment by jason0x43** [comment]
I'm working on it (because my automations broke 😁).

**Comment by jason0x43** [comment]
This is fixed in v0.6.9 (2d73d427f0d7a9442b3946bc2f8055fedaa3056f)

**Comment by SPCulhane** [comment]
> 
> 
> I'm working on it (because my automations broke 😁).

I had a feeling you may already been working on it. Thank you sir :-)
