### ISSUE TITLE
Integration failing after last HA core update

### ISSUE THREAD

**Issue by Vansmak** [jason0x43/hacs-hubitat#165]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hubitat/hub.py:242
Integration: Hubitat (documentation, issues)
First occurred: 2:05:09 PM (2 occurrences)
Last logged: 3:03:25 PM

Error setting up entry Hubitat (e064c169) for hubitat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hubitat/__init__.py", line 37, in async_setup_entry
    if not await hub.async_setup():
  File "/config/custom_components/hubitat/hub.py", line 242, in async_setup
    await self._hub.start()
  File "/usr/local/lib/python3.9/site-packages/hubitatmaker/hub.py", line 189, in start
    await self._start_server()
  File "/usr/local/lib/python3.9/site-packages/hubitatmaker/hub.py", line 459, in _start_server
    await self.set_event_url(self.event_url)
  File "/usr/local/lib/python3.9/site-packages/hubitatmaker/hub.py", line 236, in set_event_url
    await self._api_request(f"postURL/{url}")
  File "/usr/local/lib/python3.9/site-packages/hubitatmaker/hub.py", line 420, in _api_request
    raise RequestError(resp)
hubitatmaker.error.RequestError: GET http://192.168.254.xx/apps/api/1256/postURL/http:%2F%2F192.168.254.98:42169?access_token=xxxxc169-9e97-49ae-84ff-f8bbbfdxxxx - [500] Server Error

**Comment by Vansmak** [comment]
fixed itself
