### ISSUE TITLE
Hubitat Integration not loading after 2024.1.2

### ISSUE THREAD

**Issue by simondsmason** [jason0x43/hacs-hubitat#247]
I am getting the following errors in the log:

```
Setup failed for custom integration 'hubitat': Unable to import component: Exception importing custom_components.hubitat
7:46:40 AM – (ERROR) setup.py
Unexpected exception importing component custom_components.hubitat
7:46:40 AM – (ERROR) loader.py
SUPPORT_ALARM_ARM_AWAY was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
7:46:40 AM – (WARNING) Alarm control panel - message first occurred at 7:46:40 AM and shows up 8 times
Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:205
Integration: Alarm control panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 7:46:40 AM (8 occurrences)
Last logged: 7:46:40 AM
```

```
SUPPORT_ALARM_ARM_AWAY was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_ARM_HOME was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_ARM_NIGHT was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_TRIGGER was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
```

```
Logger: homeassistant.loader
Source: loader.py:822
First occurred: 7:46:40 AM (1 occurrences)
Last logged: 7:46:40 AM

Unexpected exception importing component custom_components.hubitat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/hubitat/__init__.py", line 9, in <module>
    from custom_components.hubitat.services import (
  File "/config/custom_components/hubitat/services.py", line 11, in <module>
    from .alarm_control_panel import HubitatSecurityKeypad
  File "/config/custom_components/hubitat/alarm_control_panel.py", line 23, in <module>
    from .device import HubitatEntity
  File "/config/custom_components/hubitat/device.py", line 133, in <module>
    class HubitatEntity(HubitatBase, UpdateableEntity):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

This has only started happening since I updated, which I think was yesterday.

**Comment by jason0x43** [comment]
You need to update to the latest release of the integration.

**Comment by simondsmason** [comment]
Thanks, that did the trick.  I am new to Home Assistant and assumed I would be notified about a pending update in HACS.  Turns out I have a couple of HACS that have updates available.  I'm looking around for an easy way to get notified on updates.  If you have any suggestions, please do let me know.  

And hopefully my lack of experience in this thread will be helpful for someone else!
