### ISSUE TITLE
Hubitat intergration fails to load after updating to 2024.1.6 today

### ISSUE THREAD

**Issue by dlarkinsPonderosa** [jason0x43/hacs-hubitat#253]
I have 4 instances, and none of them are loaded.

Logger: homeassistant.loader
Source: loader.py:822
First occurred: 3:06:50 PM (1 occurrences)
Last logged: 3:06:50 PM

Unexpected exception importing component custom_components.hubitat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/hubitat/__init__.py", line 9, in <module>
    from custom_components.hubitat.services import (
  File "/config/custom_components/hubitat/services.py", line 11, in <module>
    from .alarm_control_panel import HubitatSecurityKeypad
  File "/config/custom_components/hubitat/alarm_control_panel.py", line 23, in <module>
    from .device import HubitatEntity
  File "/config/custom_components/hubitat/device.py", line 133, in <module>
    class HubitatEntity(HubitatBase, UpdateableEntity):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by jason0x43** [comment]
Are you running the latest version of the integration?

**Comment by dlarkinsPonderosa** [comment]
Just came back to say I upgraded the integration and the issue was resolved! (sorry, I thought I had updated it already, but thanks for commenting so fast)

**Comment by dlarkinsPonderosa** [comment]
resolved by updating to latest version of Hubitat integration
![image](https://github.com/jason0x43/hacs-hubitat/assets/143213743/36678609-adca-41b9-857f-0a4fb0c023fb)

**Comment by dlarkinsPonderosa** [comment]
resolved by updating to latest version of Hubitat integration
![image](https://github.com/jason0x43/hacs-hubitat/assets/143213743/36678609-adca-41b9-857f-0a4fb0c023fb)
