### ISSUE TITLE
KeyError with latest HA firmware

### ISSUE THREAD

**Issue by BigWebstas** [jason0x43/hacs-hubitat#44]
```
5:38 PM KeyError: 'f9b16c1a546a437ab8661cc097234db3'
5:38 PM evt = to_event_dict(event)
5:38 PM File "/home/webstas/.homeassistant/custom_components/hubitat/device.py", line 351, in get_hub
5:38 PM CONF_TEMPERATURE_UNIT: self.temperature_unit,
5:38 PM File "/home/webstas/.homeassistant/custom_components/hubitat/device.py", line 179, in async_update_options
5:38 PM Traceback (most recent call last):
5:38 PM 2020-05-14 17:38:57 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved

**Comment by jason0x43** [comment]
What were you doing when the error occurred? Was it during startup, or were you updating options?

**Comment by jason0x43** [comment]
Closing this due to inactivity.
