### ISSUE TITLE
Aqara Button

### ISSUE THREAD

**Issue by xe1gyq** [jason0x43/hacs-hubitat#59]
>  Error doing job: Exception in callback Hub.process_event({'content': {'data': None, 'descriptionText': 'Button was single-clicked', 'deviceId': '8', 'displayName': 'Aqara Button One', ...}}) 

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/hub.py", line 163, in process_event
    listener(evt)
  File "/config/custom_components/hubitat/device.py", line 395, in handle_event
    super().handle_event(event)
  File "/config/custom_components/hubitat/device.py", line 362, in handle_event
    evt = dict(event)
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 129, in __iter__
    yield key, getattr(self, key)
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 114, in type
    return self._properties["type"]
KeyError: 'type'
```

**Comment by jason0x43** [comment]
Thanks for the detailed report!

> Once integration is completed in Home Assistant, only Aqara Sensor Battery is available.

This is expected for button controllers. The buttons themselves generate events but don't have associated entities.

> Error doing job: Exception in callback Hub.process_event({'content': {'data': None, 'descriptionText': 'Button was single-clicked', 'deviceId': '8', 'displayName': 'Aqara Button One', ...}})

When you push a button on your controller, do you see a message in the log where the event was received, before Home Assistant tried to process it? It would look something like this (but for your button device):

```
2020-08-01 19:40:10 DEBUG (MainThread) [custom_components.hubitat.device] Emitted event {'device_id': '180', 'device_name': 'Triple switch', 'attribute': 'pushed', 'value': '1', 'description': 'Triple switch button 1 was pushed', 'type': None, 'hub': 'fec5aa7d'}
```

From your error, it looks like the received event might not have a `type` property. I can work around that, but I'd like to verify if that's actually the issue.

**Comment by xe1gyq** [comment]
Thanks to you @jason0x43 for the quick response :) here you have the log of button pressed and button released:

```sh
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'pushed', 'value': '1', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Button was single-clicked', 'unit': None, 'data': None},
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Updating pushed of 8 to 1,
2020-08-02 10:01:02 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Hub.process_event({'content': {'data': None, 'descriptionText': 'Button was single-clicked', 'deviceId': '8', 'displayName': 'Aqara Button One', ...}}),
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run,
    self._context.run(self._callback, *self._args),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/hub.py", line 163, in process_event,
    listener(evt),
  File "/config/custom_components/hubitat/device.py", line 395, in handle_event,
    super().handle_event(event),
  File "/config/custom_components/hubitat/device.py", line 362, in handle_event,
    evt = dict(event),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 129, in __iter__,
    yield key, getattr(self, key),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 114, in type,
    return self._properties["type"],
KeyError: 'type',
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinTime', 'value': 'Aug 2, 2020 10:01:02 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinTime of 8 to Aug 2, 2020 10:01:02 AM,
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonPressedEpoch', 'value': '1596380462617', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonPressedEpoch', 'unit': None, 'data': None},
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonPressedEpoch of 8 to 1596380462617,
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonPressedTime', 'value': 'Aug 2, 2020 10:01:02 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonPressedTime', 'unit': None, 'data': None},
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonPressedTime of 8 to Aug 2, 2020 10:01:02 AM,
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinEpoch', 'value': '1596380462605', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:01:02 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinEpoch of 8 to 1596380462605,
```

And now of button held and button released:

```sh
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonHeldEpoch', 'value': '1596380639728', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonHeldEpoch', 'unit': None, 'data': None},
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonHeldEpoch of 8 to 1596380639728,
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinEpoch', 'value': '1596380639718', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinEpoch of 8 to 1596380639718,
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'held', 'value': '1', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Button was held', 'unit': None, 'data': None},
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Updating held of 8 to 1,
2020-08-02 10:03:59 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Hub.process_event({'content': {'data': None, 'descriptionText': 'Button was held', 'deviceId': '8', 'displayName': 'Aqara Button One', ...}}),
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run,
    self._context.run(self._callback, *self._args),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/hub.py", line 163, in process_event,
    listener(evt),
  File "/config/custom_components/hubitat/device.py", line 395, in handle_event,
    super().handle_event(event),
  File "/config/custom_components/hubitat/device.py", line 362, in handle_event,
    evt = dict(event),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 129, in __iter__,
    yield key, getattr(self, key),
  File "/usr/local/lib/python3.8/site-packages/hubitatmaker/types.py", line 114, in type,
    return self._properties["type"],
KeyError: 'type',
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonHeldTime', 'value': 'Aug 2, 2020 10:03:59 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonHeldTime', 'unit': None, 'data': None},
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonHeldTime of 8 to Aug 2, 2020 10:03:59 AM,
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinTime', 'value': 'Aug 2, 2020 10:03:59 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:03:59 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinTime of 8 to Aug 2, 2020 10:03:59 AM,
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'released', 'value': '1', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Button was released', 'unit': None, 'data': None},
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Updating released of 8 to 1,
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonReleasedEpoch', 'value': '1596380641542', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonReleasedEpoch', 'unit': None, 'data': None},
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonReleasedEpoch of 8 to 1596380641542,
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'buttonReleasedTime', 'value': 'Aug 2, 2020 10:04:01 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': 'Updated buttonReleasedTime', 'unit': None, 'data': None},
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Updating buttonReleasedTime of 8 to Aug 2, 2020 10:04:01 AM,
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinTime', 'value': 'Aug 2, 2020 10:04:01 AM', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinTime of 8 to Aug 2, 2020 10:04:01 AM,
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lastCheckinEpoch', 'value': '1596380641532', 'displayName': 'Aqara Button One', 'deviceId': '8', 'descriptionText': None, 'unit': None, 'data': None},
2020-08-02 10:04:01 DEBUG (MainThread) [hubitatmaker.hub] Updating lastCheckinEpoch of 8 to 1596380641532,
```

**Comment by AzureAzim** [comment]
I think I am having a similar problem with the Aeotec Nanomote. The nanomote only shows as a battery device. Works fine when joined to HomeAssistant via zwave directly. 
![image](https://user-images.githubusercontent.com/11980156/92310524-5ab54100-ef7d-11ea-8a3c-e0c09de16943.png)
`2020-09-05 13:38:40 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'motion', 'value': 'inactive', 'displayName': 'Upstairs Motion Sensor', 'deviceId': '167', 'descriptionText': 'Upstairs Motion Sensor: motion is inactive', 'unit': None, 'type': None, 'data': None}
2020-09-05 13:38:40 DEBUG (MainThread) [hubitatmaker.hub] Updating motion of 167 to inactive
2020-09-05 13:38:47 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'pushed', 'value': '2', 'displayName': 'HankButton', 'deviceId': '353', 'descriptionText': 'HankButton Button 2 pushed', 'unit': None, 'type': 'physical', 'data': None}
2020-09-05 13:38:47 DEBUG (MainThread) [hubitatmaker.hub] Updating pushed of 353 to 2
2020-09-05 13:38:47 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'lock', 'value': 'unlocked', 'displayName': 'Back Door Lock', 'deviceId': '289', 'descriptionText': 'Back Door Lock was unlocked by thumb turn [physical]', 'unit': None, 'type': 'physical', 'data': None}
2020-09-05 13:38:47 DEBUG (MainThread) [hubitatmaker.hub] Updating lock of 289 to unlocked
2020-09-05 13:38:48 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'contact', 'value': 'open', 'displayName': 'Back Door Sensor', 'deviceId': '129', 'descriptionText': 'Back Door Sensor was opened', 'unit': None, 'type': None, 'data': None}
2020-09-05 13:38:48 DEBUG (MainThread) [hubitatmaker.hub] Updating contact of 129 to open
2020-09-05 13:38:55 DEBUG (MainThread) [hubitatmaker.hub] Received event: {'name': 'contact', 'value': 'closed', 'displayName': 'Back Door Sensor', 'deviceId': '129', 'descriptionText': 'Back Door Sensor was closed', 'unit': None, 'type': None, 'data': None}
2020-09-05 13:38:55 DEBUG (MainThread) [hubitatmaker.hub] Updating contact of 129 to closed
`

**Comment by fxl90** [comment]
I hate to add to something that seemed solved, but I am seeing issues with these Aqara buttons and even Smartthings buttons.

Previously the hubitat integration, along with the automation UI in home assistant, would present the button events as trigger options in the UI. Seems like those options stopped being presented. Now I can only trigger on battery state but not on buttons pushed or held events.

**Comment by fxl90** [comment]
Well ignore that last statement, looks like this issue is probably my problem: #65

**Comment by jason0x43** [comment]
@xe1gyq - I published an updated version of the integration that should take care of the missing `type` property issue. Let me know if that helps.

**Comment by xe1gyq** [comment]
Thanks @AzureAzim for your comments and thanks @jason0x43 for updating the version :+1:  The integration is at my parents home and I am planning to be there early next month, I will for sure report the results.

If someone else could test, We will appreciate to get this tested and closed.

**Comment by xe1gyq** [comment]
I am still here but away from the Hubitat setup. I will arrive to my parents' home next month. So give me more time to report back. Thanks :) Sorry for the inconvenience.

**Comment by pageb018** [comment]
I just tried to add the Aqara Button and getting the same issue as above. Only the battery state is shown and no automation triggers are present. Was this ever solved?

**Comment by pageb018** [comment]
Here is the log message I am seeing 

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hubitat/device_trigger.py:246
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:55:52 PM (2 occurrences)
Last logged: 9:57:49 PM

[139981145521456] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 239, in with_error_handling
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 293, in websocket_device_automation_list_triggers
    triggers = (await _async_get_device_automations(hass, "trigger", [device_id])).get(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 175, in _async_get_device_automations
    for domain_results in await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 136, in _async_get_device_automations_from_domain
    return await asyncio.gather(
  File "/config/custom_components/hubitat/device_trigger.py", line 117, in async_get_triggers
    trigger_subtypes = get_trigger_subtypes(device, trigger_type)
  File "/config/custom_components/hubitat/device_trigger.py", line 246, in get_trigger_subtypes
    num_buttons = int(device.attributes[ATTR_NUM_BUTTONS].value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
