### ISSUE TITLE
Hangs on trying to add new integration 

### ISSUE THREAD

**Issue by Phara0h** [jason0x43/hacs-hubitat#63]
I  go to Configuration -> Integrations in the Home Assistant UI and click the “+” and it just spins forever on `Please wait while the integration is being installed`

**Comment by jason0x43** [comment]
Check the home assistant log (`<config>/home-assistant.log`) when you try to add the integration -- it should provide some information about what's going on. One possibility is that HA is having some problem installing the integration's dependencies (the `hubitatmaker` Python package); the log should show HA attempting to install that, and should indicate if there's some problem.

**Comment by ajuhawk** [comment]
`2020-09-17 20:21:02 ERROR (SyncWorker_39) [homeassistant.util.package] Unable to install package hubitatmaker>=0.3.11,<0.4.0: ERROR: Could not find a version that satisfies the requirement hubitatmaker<0.4.0,>=0.3.11 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10)
ERROR: No matching distribution found for hubitatmaker<0.4.0,>=0.3.11
2020-09-17 20:21:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 120, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 524, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 75, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 132, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for hubitat not found: ['hubitatmaker>=0.3.11,<0.4.0'].`

**Comment by jason0x43** [comment]
@ajuhawk Is this related to the issue?

**Comment by jason0x43** [comment]
Definitly @ajuhawk's issue, and possibly @Phara0h's, are related to #67. I just published a fix for that. Try installing the addon again and/or restarting HA and see if it works better this time.

**Comment by jason0x43** [comment]
Closing this a (probably) resolved
