### ISSUE TITLE
Add support for button controllers

### ISSUE THREAD

**Issue by jason0x43** [jason0x43/hacs-hubitat#7]
Add support for pushbuttons. These will work using Home Assistant's [device triggers](https://developers.home-assistant.io/docs/en/next/device_automation_trigger.html).

**Comment by mbaran5** [comment]
I am using the latest code and having this issue when adding a push button

```
Error while setting up hubitat platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/hubitat/switch.py", line 109, in async_setup_entry
    event_emitters.append(*button_controllers)
TypeError: append() takes exactly one argument (2 given)
```

**Comment by jason0x43** [comment]
That looks like a bug. I’ve opened #11 for it.
